name: Deploy

# clare all permissions for GITHUB_TOKEN
permissions: {}

on:
  workflow_call:

# allow single build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy

    if: |
      github.event_name == 'push' && 
      github.repository_owner == 'mojohaus' && 
      github.ref == 'refs/heads/master' &&
      !startsWith(github.event.head_commit.message , '[maven-release-plugin] prepare release')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
          server-id: ossrh-snapshots
          server-username: MAVEN_DEPLOY_UID
          server-password: MAVEN_DEPLOY_PWD

      - name: Set up Maven
        run:
            mvn --errors --batch-mode --show-version org.apache.maven.plugins:maven-wrapper-plugin:3.3.2:wrapper "-Dmaven=3.9.7"

      - name: Publish Snapshot
        run: ./mvnw --errors --batch-mode --show-version deploy -DskipTests
        env:
          MAVEN_DEPLOY_UID: ${{ secrets.MAVEN_DEPLOY_UID }}
          MAVEN_DEPLOY_PWD: ${{ secrets.MAVEN_DEPLOY_PWD }}
